import { VideoProject } from "@/types/videos";

export const allVideoProjects: VideoProject[] = [
  {
    id: "wedding-piyush-rojaleen",
    video_title: "Piyush & Rojaleen - Cinematic Wedding Film",
    video_description: "A high-end cinematic wedding film capturing the beautiful celebrations of Piyush & Rojaleen. Edited with premium warm color grading, seamless storytelling transitions, custom audio sync, and visual effects to create an everlasting memory.",
    tags: ["Wedding", "Cinematic Film", "Color Grading", "Video Editing"],
    cover_image: "/project-images/wedding-thumbnail.jpg",
    publish_date: "2026-07-07",
    client_name: "Piyush & Rojaleen",
    client_image: "/yogitasingh.jpg",
    client_feedback: "Beautifully captured and edited! The transitions and color grading brought all our wedding memories back to life in the most magical way.",
    video_link: "https://drive.google.com/file/d/1v3tWiTasYVowl2x9wJoUCUX4dkVKn5RF/view?usp=sharing",
    project_images: [],
    category: ["Wedding", "Event Highlight"],
    duration: "1:24",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects", "Adobe Photoshop"],
  },
  {
    id: "birthday-event-highlight",
    video_title: "Rishiv's First Birthday - Event Highlight Film",
    video_description: "A delightful, high-energy event highlight film capturing the magical celebration of Rishiv's first birthday. Edited with playful transitions, warm ambient color grading, bubble overlays, and upbeat audio synchronization.",
    tags: ["Event Highlight", "Birthday", "Playful Edit", "Color Grading"],
    cover_image: "/project-images/birthday-thumbnail.jpg",
    publish_date: "2026-07-06",
    client_name: "Rishiv's Family",
    client_image: "/yogitasingh.jpg",
    client_feedback: "It captures all the energy, fun, and little bubbles of Rishiv's special day perfectly! Love the playful pacing and transitions.",
    video_link: "https://drive.google.com/file/d/1c4KIXYUZBAfzHeUVFRfoJL3e5Zx2lu1t/view?usp=sharing",
    project_images: [],
    category: ["Event Highlight", "Shorts"],
    duration: "0:58",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects", "CapCut"],
  },
  {
    id: "cinematic-travel-reel",
    video_title: "Cinematic Travel & Lifestyle Reel",
    video_description: "A fast-paced, high-impact travel and lifestyle reel featuring dynamic transitions, color-graded aesthetic landscapes, sound design, and custom typography.",
    tags: ["Reel", "Travel", "Cinematic", "Pacing"],
    cover_image: "/project-images/travel-reel-cover.jpg",
    publish_date: "2026-07-05",
    client_name: "Travel & Co.",
    client_image: "/yogitasingh.jpg",
    client_feedback: "Incredible work! The transitions and aesthetic colors are top-tier.",
    video_link: "https://drive.google.com/file/d/1dTXlVGqtYS0GIkpDDDSQXZi_WahTPTU2/view?usp=sharing",
    project_images: [],
    category: ["Reels"],
    duration: "0:30",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects", "Color Grading"],
  },
  {
    id: "fashion-commercial-reel",
    video_title: "Modern Fashion & Commercial Reel",
    video_description: "A sleek, stylized commercial and fashion promotion reel emphasizing rhythm-sync edits, glitch effects, neon color grading, and modern beats.",
    tags: ["Reel", "Fashion", "Commercial", "Rhythm Sync"],
    cover_image: "/project-images/fashion-reel-cover.jpg",
    publish_date: "2026-07-04",
    client_name: "Vogue Styles",
    client_image: "/yogitasingh.jpg",
    client_feedback: "Super clean cuts and pacing. The editing makes the fashion video feel extremely high-end!",
    video_link: "https://drive.google.com/file/d/1-A76yX95ENSQxwPdZeOXIuxnKT1VGNXz/view?usp=sharing",
    project_images: [],
    category: ["Reels"],
    duration: "0:15",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects", "Adobe Photoshop"],
  }
];
